stages:
  - review

before_script:
  - apt-get update
  - apt-get install redis-server -y
  - redis-server --daemonize yes
  - python -V
  - pip install tox

pre-commit:
  stage: review
  image: python:3.6-buster
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files
